version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./nginx/conf.dev.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - dev

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx/conf.prod.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - prod
